export const WORD_LIST = [
  // 3 letters
  'ace', 'arc', 'ash', 'axe', 'bit', 'bug', 'cat', 'cry', 'cut', 'dim',
  'dot', 'duo', 'dye', 'ego', 'elk', 'end', 'era', 'eve', 'eye', 'fan',
  'far', 'fix', 'fly', 'fog', 'fox', 'gap', 'gel', 'gem', 'gin', 'gnu',
  'god', 'gun', 'gut', 'hex', 'hit', 'hop', 'hub', 'hum', 'ice', 'ink',
  'ion', 'ivy', 'jab', 'jam', 'jar', 'jaw', 'jet', 'jot', 'joy', 'key',
  'kit', 'lag', 'lap', 'law', 'lay', 'leg', 'lip', 'log', 'low', 'mad',
  'map', 'max', 'mix', 'mob', 'mod', 'mud', 'net', 'nod', 'nor', 'odd',
  'oil', 'old', 'orb', 'ore', 'owl', 'own', 'pad', 'pan', 'paw', 'pay',
  'pit', 'pod', 'pop', 'pro', 'pry', 'pub', 'pun', 'put', 'raw', 'ray',
  'red', 'ref', 'rig', 'rim', 'rip', 'rob', 'rod', 'rot', 'row', 'rub',
  'rum', 'run', 'rut', 'sad', 'sag', 'sap', 'saw', 'set', 'six', 'sky',
  'sly', 'sob', 'son', 'soy', 'spa', 'spy', 'sub', 'sum', 'sun', 'tab',
  'tag', 'tan', 'tap', 'tar', 'tax', 'tip', 'top', 'tow', 'try', 'tug',
  'van', 'vat', 'via', 'vim', 'vow', 'war', 'wax', 'web', 'wet', 'who',
  'wit', 'woe', 'wow', 'yak', 'yam', 'yap', 'yen', 'yet', 'yew', 'zap',
  'zen', 'zip', 'zoo',

  // 4 letters
  'acid', 'arch', 'atom', 'axis', 'bail', 'bait', 'bane', 'bare', 'bark',
  'barn', 'base', 'bash', 'bask', 'beam', 'beat', 'bile', 'bind', 'bite',
  'blade', 'blaze', 'blob', 'bloc', 'bolt', 'bond', 'bone', 'boom', 'boot',
  'bore', 'born', 'bolt', 'buck', 'bulb', 'bulk', 'burn', 'burp', 'buzz',
  'cage', 'call', 'calm', 'card', 'care', 'cast', 'cave', 'ceil', 'cell',
  'char', 'chip', 'chop', 'cite', 'city', 'clad', 'clam', 'clan', 'claw',
  'clay', 'clip', 'club', 'clue', 'coat', 'code', 'coil', 'cold', 'colt',
  'come', 'cone', 'cord', 'core', 'corn', 'cost', 'coup', 'cove', 'cowl',
  'crab', 'crew', 'crop', 'crow', 'cube', 'cuff', 'cult', 'curl', 'damp',
  'dank', 'dare', 'dark', 'dart', 'data', 'dawn', 'daze', 'dead', 'deal',
  'deck', 'deed', 'deep', 'deft', 'deny', 'dial', 'dice', 'disk', 'dive',
  'dome', 'doom', 'door', 'dope', 'dork', 'dorm', 'dose', 'dote', 'drag',
  'draw', 'drip', 'drop', 'drug', 'drum', 'dual', 'duel', 'dumb', 'dump',
  'dusk', 'dust', 'each', 'earl', 'earn', 'ease', 'edge', 'edit', 'emit',
  'epic', 'even', 'exam', 'face', 'fact', 'fade', 'fail', 'fake', 'fall',
  'fame', 'fast', 'fate', 'faze', 'feat', 'feed', 'feel', 'fell', 'felt',
  'fend', 'file', 'fill', 'film', 'find', 'fire', 'firm', 'fish', 'fist',
  'flag', 'flaw', 'flay', 'fled', 'flex', 'flip', 'flow', 'foam', 'fold',
  'font', 'fool', 'foot', 'ford', 'fore', 'fork', 'form', 'fort', 'foul',
  'four', 'free', 'fret', 'from', 'fuel', 'full', 'fume', 'fuse', 'fuss',
  'gale', 'gash', 'gate', 'gaze', 'gear', 'gild', 'gist', 'glee', 'glow',
  'glue', 'goad', 'goat', 'gold', 'gore', 'gory', 'grab', 'gram', 'grit',
  'grow', 'gulf', 'gust', 'hack', 'hail', 'halt', 'hand', 'hang', 'hard',
  'hare', 'harm', 'harp', 'hash', 'hate', 'haul', 'hawk', 'haze', 'head',
  'heal', 'heap', 'heat', 'heel', 'helm', 'hemp', 'herb', 'herd', 'hero',
  'hide', 'high', 'hill', 'hive', 'hold', 'hole', 'holm', 'holy', 'home',
  'hone', 'hoof', 'hook', 'hope', 'horn', 'host', 'howl', 'hull', 'hunt',
  'hurt', 'husk', 'idle', 'inch', 'info', 'iron', 'isle', 'itch', 'jolt',
  'jump', 'keen', 'kill', 'kind', 'king', 'knob', 'know', 'lace', 'lame',
  'land', 'lane', 'lash', 'last', 'late', 'lead', 'leaf', 'lean', 'leap',
  'left', 'lens', 'lick', 'life', 'lift', 'like', 'lime', 'line', 'link',
  'lion', 'list', 'lobe', 'lock', 'loft', 'lore', 'lure', 'lurk', 'lust',
  'made', 'main', 'make', 'mall', 'malt', 'mane', 'mark', 'mars', 'mask',
  'mass', 'mast', 'maze', 'mean', 'meet', 'melt', 'mesh', 'mild', 'mill',
  'mind', 'mine', 'mint', 'mire', 'mist', 'mode', 'mold', 'mole', 'monk',
  'moon', 'moor', 'more', 'moss', 'most', 'move', 'much', 'muck', 'muon',
  'muse', 'musk', 'must', 'myth', 'nail', 'name', 'need', 'nest', 'news',
  'next', 'nick', 'node', 'nome', 'noon', 'norm', 'note', 'noun', 'numb',
  'oath', 'once', 'only', 'open', 'orca', 'over', 'oxen', 'pace', 'pack',
  'page', 'pain', 'pair', 'pale', 'palm', 'park', 'part', 'pass', 'past',
  'path', 'peak', 'peel', 'peer', 'pelt', 'perk', 'pest', 'pick', 'pier',
  'pile', 'pill', 'pine', 'pipe', 'plan', 'play', 'plot', 'plow', 'plug',
  'plus', 'plod', 'pole', 'poll', 'pond', 'pool', 'port', 'pose', 'post',
  'pour', 'prey', 'prim', 'prod', 'prop', 'pull', 'pump', 'pure', 'push',
  'quad', 'quit', 'quiz', 'race', 'rack', 'raid', 'rail', 'rain', 'ramp',
  'rank', 'rant', 'raze', 'read', 'reel', 'rein', 'rely', 'rent', 'rest',
  'rice', 'rich', 'ride', 'rife', 'ring', 'riot', 'rise', 'risk', 'rite',
  'road', 'roam', 'roar', 'robe', 'rock', 'role', 'roll', 'roof', 'rook',
  'rope', 'rose', 'rove', 'ruin', 'rule', 'rush', 'rust', 'safe', 'saga',
  'sage', 'sail', 'sake', 'sale', 'salt', 'same', 'sand', 'sane', 'save',
  'scan', 'scar', 'seal', 'seam', 'seed', 'seek', 'seem', 'seep', 'self',
  'sell', 'send', 'sewn', 'shed', 'shin', 'ship', 'shot', 'show', 'shut',
  'sick', 'side', 'sift', 'sign', 'silk', 'silt', 'sing', 'sink', 'site',
  'size', 'slab', 'slag', 'slam', 'slap', 'slash', 'slew', 'slim', 'slip',
  'slot', 'slow', 'slug', 'snap', 'soar', 'sock', 'soft', 'soil', 'sold',
  'sole', 'some', 'sort', 'soul', 'span', 'spar', 'spin', 'spit', 'spot',
  'spun', 'stab', 'stag', 'star', 'stay', 'stem', 'step', 'stir', 'stop',
  'sting', 'stub', 'stun', 'such', 'suit', 'sunk', 'swap', 'swat', 'sway',
  'swim', 'swing', 'tail', 'take', 'tale', 'tall', 'tame', 'task', 'team',
  'tear', 'tell', 'tend', 'term', 'test', 'text', 'than', 'them', 'then',
  'this', 'thorn', 'tile', 'till', 'time', 'tint', 'tiny', 'tide', 'toll',
  'tome', 'tone', 'tool', 'torn', 'tort', 'tour', 'town', 'trap', 'trek',
  'trim', 'trio', 'trip', 'true', 'tube', 'tuft', 'tune', 'tusk', 'twin',
  'type', 'unit', 'urge', 'used', 'user', 'vane', 'veil', 'vein', 'vent',
  'verb', 'vest', 'vibe', 'vice', 'view', 'vine', 'void', 'volt', 'vote',
  'wade', 'wake', 'walk', 'wall', 'wand', 'ward', 'warm', 'warn', 'warp',
  'wave', 'weak', 'weld', 'well', 'went', 'wide', 'wild', 'will', 'wilt',
  'wind', 'wing', 'wire', 'wise', 'wish', 'with', 'woke', 'wolf', 'womb',
  'wood', 'word', 'wore', 'worm', 'worn', 'wove', 'writ', 'yard', 'year',
  'yell', 'your', 'zero', 'zone',

  // 5 letters
  'abyss', 'acute', 'agile', 'agony', 'alarm', 'algae', 'alien', 'align',
  'alloy', 'alter', 'angel', 'anger', 'angle', 'AngularMomentum', 'annex',
  'annul', 'anvil', 'apex', 'aorta', 'apple', 'apply', 'aptly', 'arena',
  'argue', 'aroma', 'array', 'arrow', 'artsy', 'ashes', 'atlas', 'atone',
  'attic', 'audio', 'audit', 'augur', 'avail', 'avant', 'avoid', 'awake',
  'awestruck', 'badly', 'banjo', 'baron', 'basis', 'batch', 'beach', 'beard',
  'beast', 'begun', 'being', 'below', 'bench', 'berth', 'bevel', 'binge',
  'biome', 'bison', 'black', 'blade', 'blame', 'bland', 'blare', 'blast',
  'blaze', 'bleak', 'blend', 'bless', 'blink', 'bliss', 'blood', 'bloom',
  'blown', 'blunt', 'blurb', 'board', 'boast', 'bogus', 'booth', 'brace',
  'braid', 'brain', 'brake', 'brand', 'brawl', 'braze', 'bread', 'break',
  'breed', 'breve', 'bribe', 'brick', 'brine', 'brink', 'broil', 'broke',
  'brook', 'brood', 'broom', 'broth', 'brown', 'brunt', 'brush', 'bulge',
  'burst', 'cable', 'cache', 'cadge', 'camel', 'canon', 'caper', 'cargo',
  'carry', 'catch', 'cause', 'cease', 'chain', 'chalk', 'champ', 'chaos',
  'charm', 'chase', 'chasm', 'cheap', 'cheat', 'check', 'cheek', 'cheer',
  'chess', 'chest', 'chief', 'child', 'chill', 'choir', 'chord', 'chose',
  'chunk', 'civic', 'civil', 'claim', 'clash', 'class', 'clean', 'clear',
  'clerk', 'click', 'cliff', 'climb', 'cling', 'cloak', 'clone', 'close',
  'cloud', 'clown', 'comet', 'comic', 'coral', 'cored', 'corps', 'count',
  'court', 'cover', 'craft', 'cramp', 'crane', 'crash', 'crawl', 'crazy',
  'creek', 'creep', 'crest', 'crime', 'crisp', 'cross', 'crowd', 'crown',
  'cruel', 'crush', 'crypt', 'curse', 'cycle', 'daily', 'decay', 'decoy',
  'delta', 'dense', 'depot', 'depth', 'derby', 'devil', 'dirge', 'dodge',
  'dogma', 'doubt', 'dowel', 'draft', 'drain', 'dread', 'dream', 'dress',
  'drift', 'drill', 'drive', 'drone', 'drove', 'drown', 'dunce', 'dying',
  'eagle', 'early', 'earth', 'easel', 'edged', 'eight', 'eject', 'elect',
  'elite', 'ember', 'empty', 'enact', 'enemy', 'engle', 'enjoy', 'ensue',
  'enter', 'entry', 'envoy', 'equal', 'erupt', 'ether', 'evade', 'event',
  'exact', 'exert', 'exile', 'exist', 'expel', 'extra', 'exult', 'fable',
  'facet', 'faith', 'false', 'fancy', 'fangs', 'fatal', 'fault', 'feast',
  'field', 'fiend', 'fifth', 'fifty', 'fight', 'final', 'fixed', 'flame',
  'flank', 'flare', 'flesh', 'flick', 'fling', 'flint', 'flirt', 'flock',
  'flood', 'floor', 'flora', 'floss', 'flour', 'flown', 'fluke', 'flume',
  'flush', 'flute', 'focal', 'force', 'forge', 'found', 'frame', 'frank',
  'fraud', 'freed', 'fresh', 'frill', 'frisk', 'front', 'frost', 'froth',
  'frown', 'froze', 'fungi', 'gamma', 'gauge', 'gavel', 'gears', 'genre',
  'ghost', 'gilds', 'girth', 'given', 'gland', 'glare', 'glass', 'gleam',
  'glide', 'glint', 'globe', 'gloom', 'gloss', 'glove', 'going', 'grace',
  'grade', 'grand', 'grant', 'grasp', 'grass', 'grave', 'graze', 'greed',
  'greet', 'grind', 'groan', 'groom', 'groove', 'gross', 'grout', 'growl',
  'gruel', 'gruff', 'guard', 'guise', 'gulch', 'gulag', 'gusto', 'gusts',
  'habit', 'haunt', 'haven', 'havoc', 'heavy', 'helix', 'hence', 'horde',
  'hoist', 'hover', 'human', 'humor', 'hyper', 'ideal', 'image', 'imply',
  'infer', 'inner', 'input', 'inset', 'intel', 'inter', 'intro', 'inure',
  'joust', 'judas', 'judge', 'juice', 'karma', 'kinky', 'kneel', 'knell',
  'lapse', 'large', 'laser', 'latch', 'later', 'latte', 'laugh', 'layer',
  'learn', 'ledge', 'level', 'lever', 'light', 'lilac', 'limit', 'lithe',
  'liver', 'lodge', 'logic', 'loose', 'lumen', 'lunar', 'lurch', 'lyric',
  'magic', 'major', 'manor', 'march', 'marsh', 'match', 'media', 'mercy',
  'merge', 'merit', 'metal', 'might', 'minor', 'minus', 'mixer', 'model',
  'money', 'month', 'moody', 'morph', 'motor', 'mound', 'mount', 'mourn',
  'mouth', 'mural', 'naive', 'nerve', 'never', 'night', 'ninja', 'noise',
  'north', 'novel', 'nymph', 'ocean', 'offer', 'omega', 'onset', 'order',
  'organ', 'other', 'ounce', 'outer', 'outdo', 'oxide', 'ozone', 'paint',
  'panel', 'panic', 'parse', 'patch', 'pause', 'peace', 'pearl', 'pedal',
  'perch', 'peril', 'phase', 'pixel', 'pivot', 'place', 'plain', 'plane',
  'plant', 'plate', 'plaza', 'plead', 'pluck', 'plume', 'plunge', 'point',
  'poise', 'poker', 'polar', 'power', 'press', 'price', 'pride', 'prime',
  'privy', 'probe', 'proof', 'prose', 'prowl', 'proxy', 'prune', 'pulse',
  'purge', 'query', 'quest', 'queue', 'quota', 'quote', 'radar', 'radix',
  'raise', 'rally', 'range', 'rapid', 'raven', 'reach', 'realm', 'rebel',
  'reign', 'relay', 'relic', 'remix', 'rerun', 'reset', 'resin', 'rider',
  'ridge', 'rifle', 'risky', 'rival', 'river', 'rivet', 'roast', 'robin',
  'robot', 'rogue', 'rough', 'round', 'route', 'rowan', 'royal', 'rupee',
  'rupture', 'rural', 'sabre', 'salvo', 'sandy', 'sarge', 'sauce', 'scale',
  'scene', 'scope', 'score', 'scout', 'scowl', 'scrap', 'scree', 'screw',
  'scrub', 'seize', 'serve', 'setup', 'seven', 'sever', 'shade', 'shaft',
  'shake', 'shale', 'shame', 'shape', 'share', 'shark', 'sharp', 'sheen',
  'sheer', 'shelf', 'shell', 'shift', 'shine', 'shock', 'short', 'shout',
  'shove', 'siege', 'sight', 'sinew', 'sixth', 'sixty', 'skate', 'skill',
  'skull', 'slain', 'slant', 'slash', 'slave', 'sleep', 'sleet', 'slide',
  'slope', 'smart', 'smash', 'smear', 'smell', 'smile', 'smoke', 'snare',
  'sneak', 'solar', 'solve', 'sonic', 'sorry', 'south', 'space', 'spawn',
  'spear', 'speed', 'spend', 'spire', 'spite', 'spore', 'spray', 'squad',
  'stack', 'staff', 'stage', 'stain', 'stake', 'stale', 'stall', 'stamp',
  'stand', 'stark', 'start', 'state', 'stave', 'steal', 'steam', 'steel',
  'steep', 'steer', 'stern', 'stick', 'stiff', 'still', 'stock', 'stone',
  'storm', 'story', 'stomp', 'strap', 'straw', 'stray', 'strip', 'stuck',
  'study', 'stump', 'swamp', 'sweep', 'sweet', 'swept', 'swift', 'sword',
  'table', 'taunt', 'tense', 'tenth', 'terra', 'terse', 'theme', 'there',
  'thick', 'thing', 'think', 'third', 'thorn', 'those', 'three', 'threw',
  'throw', 'thump', 'tiger', 'title', 'toast', 'token', 'torso', 'total',
  'touch', 'tough', 'tower', 'track', 'trade', 'trail', 'train', 'trait',
  'tramp', 'trash', 'treed', 'trial', 'tribe', 'trick', 'tried', 'troop',
  'trove', 'truce', 'truly', 'trump', 'trunk', 'trust', 'truth', 'tumor',
  'tuner', 'twirl', 'twist', 'ultra', 'umbra', 'under', 'unify', 'union',
  'unlit', 'until', 'upper', 'upset', 'usage', 'valor', 'valve', 'vapor',
  'vault', 'visor', 'vital', 'vivid', 'vixen', 'voice', 'vomit', 'vouch',
  'vulge', 'watch', 'water', 'weave', 'wedge', 'weigh', 'weird', 'where',
  'which', 'while', 'white', 'whole', 'whose', 'wield', 'witch', 'woman',
  'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'wrath',
  'wreck', 'wring', 'wrong', 'xenon', 'yacht', 'yield', 'young', 'youth',
  'zebra',

  // 6 letters
  'ablaze', 'absurd', 'accent', 'access', 'across', 'action', 'active', 'actual',
  'adjust', 'admire', 'advent', 'aerial', 'affect', 'afford', 'afraid', 'agency',
  'agenda', 'agreed', 'allied', 'almost', 'ambush', 'amount', 'anchor', 'ancient',
  'anemia', 'animal', 'answer', 'armour', 'around', 'arrive', 'ascend', 'aspect',
  'assail', 'astral', 'atomic', 'attack', 'attain', 'avenge', 'baffled', 'bandit',
  'battle', 'beacon', 'behave', 'behind', 'binary', 'bionic', 'bishop', 'bitter',
  'bladed', 'blazed', 'blizzard', 'bloody', 'bonded', 'border', 'bounce', 'breech',
  'bridge', 'brutal', 'bullet', 'bundle', 'cannon', 'carbon', 'castle', 'cavern',
  'cipher', 'citadel', 'combat', 'comet', 'commit', 'compact', 'cosmos', 'crater',
  'crimson', 'crisis', 'crusade', 'crypt', 'cursor', 'cyborg', 'dagger', 'damage',
  'danger', 'debris', 'defend', 'detect', 'device', 'divide', 'domain', 'driven',
  'dwarfs', 'dynamo', 'efface', 'effect', 'effort', 'embark', 'empire', 'encode',
  'endure', 'energy', 'engage', 'engine', 'enigma', 'entity', 'envied', 'errant',
  'escape', 'evolve', 'exceed', 'expand', 'expire', 'export', 'expose', 'extend',
  'fallen', 'famine', 'fathom', 'fender', 'fester', 'filter', 'finale', 'finite',
  'fission', 'flurry', 'flying', 'follow', 'forest', 'frozen', 'fusing', 'fusion',
  'future', 'galaxy', 'gambit', 'garble', 'gather', 'genius', 'glitch', 'global',
  'goblin', 'govern', 'ground', 'gunner', 'hammer', 'hazard', 'hollow', 'hunter',
  'hybrid', 'impact', 'impose', 'ignite', 'illusion', 'insane', 'insert', 'intent',
  'invade', 'jester', 'joiner', 'kindle', 'knight', 'labyrinth', 'launch', 'legend',
  'lethal', 'linear', 'liquid', 'lurker', 'machine', 'madness', 'magnet', 'malice',
  'marker', 'matrix', 'menace', 'meteor', 'mirror', 'missile', 'mobile', 'mortal',
  'motion', 'mutate', 'mystic', 'nebula', 'nemesis', 'neural', 'nexus', 'nimble',
  'normal', 'nosing', 'obsess', 'obtuse', 'occupy', 'offset', 'oracle', 'outlaw',
  'output', 'outrun', 'overdo', 'overkill', 'patrol', 'pillar', 'pirate', 'planet',
  'plasma', 'poison', 'portal', 'potion', 'preset', 'primal', 'prison', 'proton',
  'pulsar', 'pursue', 'quasar', 'radial', 'radius', 'raptor', 'ravage', 'reboot',
  'record', 'reduce', 'reflex', 'refuge', 'remote', 'remove', 'repath', 'resist',
  'revive', 'revolt', 'ritual', 'rocket', 'roping', 'rubble', 'savage', 'sector',
  'shadow', 'shield', 'signal', 'silver', 'sleuth', 'sniper', 'source', 'sphere',
  'spiral', 'spirit', 'splice', 'sprint', 'static', 'stealth', 'strike', 'string',
  'subdue', 'summit', 'sunken', 'sunset', 'swivel', 'switch', 'symbol', 'syntax',
  'system', 'target', 'techno', 'tensor', 'terror', 'thrust', 'timber', 'titans',
  'torque', 'tracer', 'trance', 'trauma', 'triage', 'trigger', 'trophy', 'tunnel',
  'turret', 'tyrant', 'unique', 'unlock', 'update', 'uproot', 'upward', 'urgent',
  'vector', 'vortex', 'vulcan', 'warden', 'weapon', 'wiring', 'wizard', 'wraith',
  'zapper', 'zealot', 'zenith',

  // 7 letters
  'arsenal', 'barrage', 'torpedo', 'warpath', 'abysmal', 'brigade', 'cloaked',
  'condemn', 'contact', 'control', 'courier', 'defiant', 'descent', 'devoted',
  'distort', 'divided', 'enforce', 'evasive', 'exhaust', 'exposed', 'faction',
  'failure', 'fanatic', 'fortify', 'frontal', 'hunting', 'implant', 'inferno',
  'outcome', 'outpost', 'platoon', 'protect', 'prowler', 'pursuit', 'raiding',
  'rampant', 'rampage', 'revival', 'rollout', 'spartan', 'thunder', 'traitor',
  'veteran', 'wrangle',

  // 7-9 letters (for harder waves)
  'abscond', 'abscess', 'absolve', 'account', 'achieve', 'acquire', 'address',
  'advance', 'altered', 'android', 'annihil', 'anomaly', 'assault', 'astroid',
  'augment', 'barrier', 'berserk', 'blaster', 'blazing', 'cavalry', 'circuit',
  'cluster', 'coating', 'command', 'compile', 'corrupt', 'counter', 'coverup',
  'crackle', 'crushed', 'crystal', 'decrypt', 'deflect', 'defense', 'degrade',
  'deliver', 'destroy', 'digital', 'disable', 'discord', 'dormant', 'eclipse',
  'element', 'encrypt', 'epsilon', 'essence', 'evasion', 'execute', 'exploit',
  'extreme', 'fissure', 'flicker', 'fractal', 'fragile', 'gateway', 'gladius',
  'gravity', 'harvest', 'hazards', 'hostile', 'ignited', 'illicit', 'implode',
  'impulse', 'include', 'inspire', 'integer', 'javelin', 'junkyard', 'kinetic',
  'lashing', 'lattice', 'lighten', 'linking', 'missile', 'monarch', 'monitor',
  'monster', 'network', 'nuclear', 'obscure', 'overrun', 'package', 'partial',
  'pattern', 'payload', 'phantom', 'physics', 'pointer', 'polaris', 'possess',
  'quantum', 'radiant', 'ravaged', 'reactor', 'reentry', 'release', 'reptile',
  'reserve', 'reshape', 'resolve', 'restore', 'rewrite', 'ricochet', 'runtime',
  'scanner', 'searing', 'segment', 'seismic', 'session', 'shelter', 'shimmer',
  'silence', 'skeletal', 'smoldering', 'soldier', 'specter', 'splinter', 'station',
  'stealth', 'subject', 'subzero', 'support', 'surface', 'survive', 'systemic',
  'tactical', 'tempest', 'terminal', 'tethered', 'thermal', 'titanium', 'toxin',
  'tracker', 'trinity', 'turmoil', 'twisted', 'unknown', 'uprising', 'verdict',
  'voltage', 'warrior', 'wasteland', 'warhead', 'watcher', 'warzone',

  // 8 letters
  'blackout', 'commando', 'conquest', 'critical', 'crossbow', 'deadzone',
  'detonate', 'dropzone', 'dystopia', 'fallback', 'feedback', 'freefall',
  'gauntlet', 'gridlock', 'gunpoint', 'hardened', 'headshot', 'hellfire',
  'ignition', 'incoming', 'infernal', 'ironclad', 'launcher', 'meltdown',
  'militant', 'outburst', 'outflank', 'overload', 'perilous', 'platform',
  'priority', 'pursuing', 'radiance', 'reckless', 'remnants', 'sabotage',
  'scramble', 'sentinel', 'shrapnel', 'skirmish', 'standoff', 'submerge',
  'suppress', 'surgical', 'throttle', 'tracking', 'volatile', 'warfront',
  'whiplash', 'wildfire', 'withdraw', 'wolfpack',

  // 9-12 letters (end-game extended)
  'aftershock', 'aggression', 'apocalypse', 'armageddon', 'bombardment',
  'camouflage', 'catastrophe', 'combustion', 'conspiracy', 'decimation',
  'demolition', 'detonation', 'devastation', 'earthquake', 'escalation',
  'extinction', 'fortified', 'guerrilla', 'headhunter', 'hurricane',
  'implosion', 'incendiary', 'infiltrate', 'insurgency', 'irradiate',
  'juggernaut', 'lethality', 'malfunction', 'overthrown', 'predatory',
  'retaliate', 'shattered', 'shieldwall', 'stormfront', 'subjugate',
  'supernova', 'supersonic', 'thunderbolt', 'trailblazer', 'termination',
  'underworld', 'unleashing', 'voidwalker', 'warmonger', 'wavelength',
  'whirlwind', 'berserker', 'cataclysm', 'chainreact', 'cryogenic',
  'darkmaster', 'deathstrike', 'dreadnaught', 'deathmarch', 'firestarter',
  'floodgate', 'forbidden', 'frostbite', 'gladiator', 'grenadier',
  'hammerfall', 'immolation', 'intercept', 'ironforge', 'labyrinth',
  'lightning', 'machinegun', 'maelstrom', 'manifested', 'meltingpoint',
  'obliterate', 'pathogenic', 'powersurge', 'ramification', 'rebellion',
  'replication', 'shockblast', 'shadowstep', 'slaughter', 'smoldering',
  'stormwall', 'supersede', 'tachyonic', 'thermonuke', 'titanslayer',
  'transmute', 'trembling', 'undertow', 'unstoppable', 'vaporize',
  'venomstrike', 'vibrations', 'warpfield', 'xenoform', 'zerohour',

  // 8-10 letters (end-game)
  'absolute', 'activate', 'adaptive', 'afterburn', 'allocate', 'ambiance',
  'amplified', 'annihilate', 'anomalous', 'antimatter', 'assembly', 'barricade',
  'blackhole', 'breakdown', 'calculate', 'calibrate', 'cataclysm', 'celestial',
  'chainsaw', 'chronicle', 'circuitry', 'civilian', 'collapse', 'colonial',
  'combative', 'command', 'computing', 'construct', 'contagion', 'continuum',
  'converge', 'corridor', 'corrupted', 'crossfire', 'darkfield', 'datastream',
  'deception', 'decompose', 'defensive', 'desolate', 'disarray', 'dismantle',
  'dispatch', 'displace', 'disruptor', 'dissolve', 'dominate', 'downfall',
  'dreadful', 'dumpster', 'dynacraft', 'eldritch', 'electric', 'eliminate',
  'emergence', 'emphasize', 'energized', 'enforcer', 'enigmatic', 'entangle',
  'epidemic', 'eradicate', 'eruption', 'escalate', 'estimate', 'eviscerate',
  'evolving', 'exorcism', 'expedient', 'explosive', 'exposure', 'exponent',
  'firestorm', 'firewall', 'forcewave', 'fortrall', 'fracture', 'freezing',
  'frontline', 'galactic', 'genocide', 'ghostly', 'glitched', 'graviton',
  'grimoire', 'hardcode', 'hardcore', 'hologram', 'horsepower', 'hostility',
  'hyperlink', 'hypernova', 'hypocrisy', 'icebreaker', 'immolate', 'impacted',
  'infected', 'infinite', 'infrared', 'injected', 'integral', 'intercept',
  'isolated', 'jailbreak', 'judgment', 'kinetics', 'labyrinth', 'laserbeam',
  'lockdown', 'logistics', 'maelstrom', 'magnetic', 'malefic', 'manifest',
  'mayhem', 'megabyte', 'mercenary', 'military', 'molecular', 'momentum',
  'mutation', 'navigate', 'neonflux', 'nitrogen', 'obliterate', 'obsidian',
  'offensive', 'omniwave', 'organism', 'overcharge', 'overdrive', 'override',
  'pandemic', 'particle', 'pathogen', 'petrified', 'phosphor', 'pipeline',
  'plasmatic', 'plutonium', 'pointless', 'polarize', 'powerline', 'protocol',
  'psionic', 'psychotic', 'purgatory', 'radiation', 'railgun', 'rainfall',
  'recharge', 'recombine', 'redirect', 'regiment', 'reinforced', 'rekindle',
  'repulse', 'resonance', 'retrieve', 'retrograde', 'robotics', 'rockslide',
  'scatterbomb', 'scenario', 'scourge', 'sequence', 'shockwave', 'shutdown',
  'singularity', 'skeleton', 'slaughter', 'smoldering', 'snapshot', 'soldier',
  'spectrum', 'stardust', 'starfall', 'stargaze', 'static', 'stormwall',
  'stratosphere', 'subspace', 'sunshine', 'survivor', 'synthetic', 'tactical',
  'tailspin', 'takeover', 'targeted', 'terminus', 'terrible', 'thousand',
  'threshold', 'titanfall', 'together', 'toxicity', 'transform', 'transmit',
  'traverse', 'trespass', 'turbojet', 'tyrannic', 'ultrawave', 'undertow',
  'unstable', 'vaccinate', 'vandalism', 'velocity', 'vigilant', 'wipeout',
  'warcraft', 'wasteland', 'wormhole', 'xenolith',

  // ── Game titles ──────────────────────────────────────────────────────────────
  // 3-4 letters
  'halo', 'doom', 'pong', 'prey',
  // 5 letters
  'quake', 'metro', 'fable',
  // 6-7 letters
  'hitman', 'portal', 'hollow', 'skyrim', 'sekiro', 'diablo',
  'celeste', 'metroid', 'stalker', 'fallout',
  // 7 letters
  'witcher', 'remnant', 'destiny', 'terraria', 'warframe', 'bioshock',
  'returnal', 'fortnite', 'valorant',
  // 8-10 letters
  'deathloop', 'minecraft', 'overwatch', 'undertale', 'titanfall',
  'bloodborne', 'cyberpunk', 'starcraft', 'borderlands',

  // ── Band names ───────────────────────────────────────────────────────────────
  // 3-4 letters
  'muse', 'tool', 'rush', 'korn', 'blur', 'kiss', 'hole', 'devo', 'ween',
  // 5 letters
  'queen', 'cream', 'clash', 'tesla', 'primus', 'pixies',
  // 6 letters
  'exodus', 'slayer', 'priest', 'maiden', 'thrice', 'saosin', 'coheed',
  'atreyu', 'fugazi', 'rancid', 'morbid',
  // 7 letters
  'nirvana', 'pantera', 'sabbath', 'prodigy', 'anthrax', 'kreator',
  'incubus', 'emperor', 'chevelle',
  // 8-10 letters
  'mastodon', 'slipknot', 'megadeth', 'obituary', 'deftones', 'paramore',
  'enslaved', 'agalloch', 'converge', 'neurosis', 'evanescence',
  'satyricon', 'audioslave', 'dragonforce', 'soundgarden', 'behemoth',
  'metallica', 'radiohead', 'nightwish', 'powerwolf', 'deafheaven',

  // ── Song titles ──────────────────────────────────────────────────────────────
  // 4-5 letters
  'numb', 'creep', 'roxanne',
  // 6-7 letters
  'psycho', 'hysteria', 'starlight', 'paranoid', 'thriller', 'imagine',
  'respect', 'hallelujah', 'stronger', 'natural', 'believer', 'demons',
  'madness', 'pressure', 'sunburn', 'survival', 'reapers', 'defector',
  'algorithm', 'blockout', 'supremacy', 'aftermath', 'stockholm',
  'radioactive', 'invincible', 'resistance', 'chandelier',
];

if (typeof module !== 'undefined' && module.exports) module.exports = WORD_LIST;
